export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const SEND_POST_START = "SEND_POST_START";
export const SEND_POST_SUCCESS = "SEND_POST_SUCCESS";
export const SEND_POST_ERROR = "SEND_POST_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";

export const USER_SET = "USER_SET";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DELETE_POST_START = "USER_DELETE_POST_START";
export const USER_DELETE_POST_SUCCESS = "USER_DELETE_POST_SUCCESS";
export const USER_DELETE_POST_ERROR = "USER_DELETE_POST_ERROR";

export const USER_TOGGLE_EDIT = "USER_TOGGLE_EDIT";

export const USER_EDIT_POST_START = "USER_EDIT_POST_START";
export const USER_EDIT_POST_SUCCESS = "USER_EDIT_POST_SUCCESS";
export const USER_EDIT_POST_ERROR = "USER_EDIT_POST_ERROR";

export const FETCH_POST_START = "FETCH_POST_START";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_ERROR = "FETCH_POST_ERROR";
