export const FETCH_POSTS_START = "FETCH_POSTS_START";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";

export const SEND_POST_START = "SEND_POST_START";
export const SEND_POST_SUCCESS = "SEND_POST_SUCCESS";
export const SEND_POST_ERROR = "SEND_POST_ERROR";
